# Generated by Django 4.2.4 on 2023-08-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("isbnno", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "technology"),
                            ("general", "general"),
                            ("programming", "programming"),
                            ("science", "science"),
                            ("novel", "novel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.FloatField()),
                ("qty", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_borrow", models.DateField()),
                ("date_due", models.DateField()),
                ("days_on_books", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("idno", models.CharField(max_length=100)),
                ("prnno", models.CharField(max_length=100)),
                (
                    "member_type",
                    models.CharField(
                        choices=[("teacher", "teacher"), ("student", "student")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_date", models.DateField()),
                ("charges", models.IntegerField()),
                (
                    "dateoverdue",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")], max_length=50
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.loan"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loan",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.member"
            ),
        ),
    ]
